### ISSUE TITLE
Zoom out interaction breaks web map with GeoTIFF

### ISSUE THREAD

**Issue by drnextgis** [openlayers/openlayers#13053]
If zoom out a web map with GeoTIFF layer added on it then at some point in time all layers are gone. JSFiddle with reproducible example: https://jsfiddle.net/7kyfL3za/1/ 

https://user-images.githubusercontent.com/866124/143831348-b4aaad00-b483-4aaa-bdd6-bf5978694db9.mp4

**Comment by ahocevar** [comment]
This was fixed with the context sharing added in #12965.

**Comment by drnextgis** [comment]
Great! Looking forward to the new release!

Can I please ask one more question here. Is there a way to disable GeoTIFF rendering outside of the image boundaries for rasters without nodata value?

**Comment by tschaub** [comment]
@drnextgis if you want to, you can try out the context sharing now on the `ol@dev` release.

Regarding nodata values, if they are advertised in the GeoTIFF headers, they should be transparent.  Otherwise you can include a `nodata` property in the source configuration (next to the `url`).

**Comment by tschaub** [comment]
I still see a problem when zooming out using the latest.  We'll leave this open to investigate.

**Comment by drnextgis** [comment]
Thanks @tschaub! It is very clear how nodata works. My main concern was regarding the areas outside of the image boundaries. Is there a way to prevent OL to render them? In some cases the nodata value is not advertised and we don't know it advance to set it manually. It is ok to have these dark areas inside the image extent but not outside of it.

**Comment by tschaub** [comment]
Here is what the example looks like when I add `nodata: 0` to the source configuration:
![image](https://user-images.githubusercontent.com/41094/143903106-2c83ce9c-5a51-4bb9-99ad-e998d3d0fb93.png)

If you are seeing something different, it may have been addressed by https://github.com/geotiffjs/geotiff.js/pull/248.

**Comment by drnextgis** [comment]
So it turns out that preventing pixels be rendered outside of the image boundaries can be achieved only via `nodata` property? The thing is I don't know `nodata` in advance and I would like OL to render it like this (by respecting boundaries of the raster):
![image](https://user-images.githubusercontent.com/866124/143904563-8853d8a7-9631-42c7-af3c-f7760b60b577.png)

**Comment by tschaub** [comment]
Ideally the nodata value is present in the GeoTIFF header, so you don't need to configure it at all - but unfortunately we cannot rely on this either.

I agree it would be nice to discard pixels outside the image extent altogether.  This is another thing to look into.

**Comment by tschaub** [comment]
@drnextgis - One complicating issue with the data in your example is that it has non-square pixels.  The resolution of the reference image is `[0.0714315232981, -0.0716036222711, 0]`.  The GeoTIFF source currently makes the assumption that pixels are square.

**Comment by tschaub** [comment]
With the changes in #13060, the issues zooming out are gone.  Data outside the image extent is not loaded, but because the y-resolution doesn't equal the x-resolution, we end up thinking there are a few extra rows of pixels at the bottom of the image, so a whole extra row of tiles is rendered black along the bottom.  This would be improved if the pixels were square.  And there would be no black pixels if the `nodata` value were included in the GeoTIFF metadata (which happens with [GDAL's `SetNoDataValue`](https://gdal.org/api/gdalrasterband_cpp.html#_CPPv4N14GDALRasterBand14SetNoDataValueEd) or equivalent).

![less-nodata-low](https://user-images.githubusercontent.com/41094/144143326-8a78dae0-9069-4b19-b00a-84fe29bfa6ff.gif)

**Comment by drnextgis** [comment]
Awesome! Great job! Do you consider enabling support of non-square pixels (not so common case though)?

**Comment by tschaub** [comment]
@drnextgis - That would require a significant change to the library.  We currently treat `resolution` as a single, scalar value in many places.

**Comment by tschaub** [comment]
@drnextgis - support for non-square pixels added in #13648

**Comment by drnextgis** [comment]
That is amazing, thanks for letting me know!
