### ISSUE TITLE
Vector tile source format type MVT doesn't accept - format: new MVT({ featureClass: Feature })

### ISSUE THREAD

**Issue by Zoom1611** [openlayers/openlayers#15929]
I updated OL version to latest version of 9.2.4. When created vector tile source in the previous version I used (9.1.0), TS format definition allowed the definition of MVT format like this:
```js
const vectorTileSource = new VectorTileSource({
    format: new MVT({ featureClass: Feature }),
    url: layer.url,
});
```
Now I get a TS error that I can only define the MVT format as `RenderFeature`.

I found out that this error happened on version 9.2.2.

Looking at your documentation for the latest version, it appears that MVT should be able to receive `{ featureClass: Feature }`, however a TS error occurs.

From your documentation for MVT:

| property      | desc |
| ----------- | ----------- |
| featureClass      | Class for features returned by [readFeatures](https://openlayers.org/en/latest/apidoc/module-ol_format_MVT-MVT.html#readFeatures). Set to [Feature](https://openlayers.org/en/latest/apidoc/module-ol_Feature-Feature.html) to get full editing and geometry support at the cost of decreased rendering performance. The default is [RenderFeature](https://openlayers.org/en/latest/apidoc/module-ol_render_Feature-RenderFeature.html), which is optimized for rendering and hit detection.       |

TS error:
```js
Type 'MVT<typeof Feature>' is not assignable to type 'FeatureFormat<typeof RenderFeature>'.
  Types of property 'featureClass' are incompatible.
    Type 'typeof Feature' is not assignable to type 'typeof RenderFeature'.
      Types of construct signatures are incompatible.
        Type 'new <Geometry extends Geometry = Geometry>(geometryOrProperties?: Geometry | ObjectWithGeometry<Geometry> | undefined) => Feature<Geometry>' is not assignable to type 'new (type: Type, flatCoordinates: number[], ends: number[], stride: number, properties: { [x: string]: any; }, id: string | number | undefined) => RenderFeature'.
          Types of parameters 'geometryOrProperties' and 'type' are incompatible.
            Type 'Type' is not assignable to type 'Geometry | ObjectWithGeometry<Geometry> | undefined'.
              Type '"Point"' is not assignable to type 'Geometry | ObjectWithGeometry<Geometry> | undefined'.
```

**Comment by ahocevar** [comment]
Please use `ol@dev` - the issue is fixed there.

**Comment by mkf62** [comment]
Maybe I'm doing something wrong somehow, but I just `npm install ol` to get version 10.4 and I have typescript `5.7.2` installed as well. Still looks like this issue hasn't been pushed to production as I get a red squiggly under `featureClass` property of the `MVT` class stating a similar error.

```javascript
import { VectorTile as VectorTileSource } from 'ol/source'

const vts = new VectorTileSource({
        url: 'https://my-url-is-here.com/geoserver/xyz/whatever',
        format: new MVT({
            featureClass: Feature,
            idProperty: idField,
        }),
        tileGrid: tileGrid,
})
```

```
Type 'typeof Feature' is not assignable to type 'typeof RenderFeature'.
  Types of construct signatures are incompatible.
    Type 'new <Geometry extends Geometry = Geometry>(geometryOrProperties?: Geometry | ObjectWithGeometry<Geometry>) => Feature<...>' is not assignable to type 'new (type: Type, flatCoordinates: number[], ends: number[], stride: number, properties: { [x: string]: any; }, id: string | number) => RenderFeature'.
      Types of parameters 'geometryOrProperties' and 'type' are incompatible.
        Type 'string' is not assignable to type 'Geometry | ObjectWithGeometry<Geometry>'.
          Type 'string' is not assignable to type 'Geometry | ObjectWithGeometry<Geometry>'.ts(2322)
MVT.d.ts(9, 5): The expected type comes from property 'featureClass' which is declared here on type 'Options<RenderFeature>'
(property) featureClass?: typeof RenderFeature
```

**Comment by ahocevar** [comment]
This is a simliar issue, which we also fixed in the meantime, but it's not yet in a release in the `latest` channel. Try `npm install ol@dev` again.

**Comment by Zoom1611** [comment]
@ahocevar I worked with 9.1.0 version until now because of this issue and i think it is finally time to go to latest version. I came back to this and tried as you said  `npm install ol@dev` and issue is still there. Also, on latest version of 10.5.0 this issue still exists.
